# version: '3'

# services:
#   web:
#     build: .
#     depends_on:
#       - db
#     volumes:
#       - ./:/code:ro
#     environment:
#       - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/amharic_llm
#     ports:
#       - "8000:80"

#   db:
#       image: postgres:15-alpine
#       volumes:
#         - postgres_data:/var/lib/postgresql/data/
#       expose:
#         - 5433
#       environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_DB=amharic_llm

# volumes:
#       postgres_data: 


#       version: '3.8'

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./api:/code/api
    environment:
      - PORT=80
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
 
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
